version: '3'

services:
  route:
    image: local/spine-directory-service:${BUILD_TAG}
    ports:
        - "8080:80"
    environment:
      - MHS_LOG_LEVEL=NOTSET
      - MHS_SDS_URL=ldap://192.168.128.11
      - MHS_SDS_SEARCH_BASE=ou=services,o=nhs
      - MHS_DISABLE_SDS_TLS=True
      - MHS_SDS_REDIS_CACHE_HOST=redis
      - MHS_SDS_REDIS_DISABLE_TLS=True
  redis:
    image: redis
    ports:
      - "6379:6379"