name: "$(SourceBranchName)+$(BuildID)"

trigger:
    branches:
        include:
            - tags/refs/v*
    tags:
        include:
            - v*

pr:
    branches:
        include: ["*"]

resources:
    repositories:
        - repository: common
          type: github
          name: NHSDigital/api-management-utils
          ref: refs/heads/edge
          endpoint: NHSDigital

variables:
    - template: project.yml

extends:
    template: azure/common/apigee-build.yml@common

    parameters:
        python_version: ${{ variables.python_version }}
        service_name: ${{ variables.service_name }}
        short_service_name: ${{ variables.short_service_name }}
        cache_steps:
            - bash: |
                  PATCH=$(curl -s https://api.github.com/repos/actions/python-versions/tags?per_page=100 \
                      | jq -r '[.[] | .name | select(startswith("3.8"))] | sort -V | tail -n 1 | cut -d- -f1')
                  PATCH=$(
                    curl -s "https://api.github.com/repos/actions/python-versions/tags?per_page=100" \
                    | jq -r '
                        [.[] | .name | select(startswith("3.8"))]
                        | sort
                        | last
                        | (split("-"))[0]
                      '
                  )
                  echo "Resolved latest python version: $PATCH"
                  echo "##vso[task.setvariable variable=LD_LIBRARY_PATH;]/agent/_work/_tool/Python/${PATCH}/x64/lib/"
              displayName: "Query and set python tool cache path"

            - task: UsePythonVersion@0
              displayName: "Use Python ${{ variables.python_version }}"
              inputs:
                  versionSpec: ${{ variables.python_version }}

            - bash: |
                  echo "Checking the python version in use to set LD_LIBRARY_PATH"
                  echo "Python location: $(UsePy.pythonLocation)"
                  echo "##vso[task.setvariable variable=LD_LIBRARY_PATH]$(UsePy.pythonLocation)/lib"
              displayName: "Set LD_LIBRARY_PATH"

            - task: s3-cache-action@1
              inputs:
                  key: "node modules | ${{ variables.service_name }} | ${{ variables.service_name }}/package-lock.json"
                  location: "${{ variables.service_name }}/node_modules"
                  debug: true
              displayName: cache node modules
            - task: s3-cache-action@1
              inputs:
                  key: "poetry | ${{ variables.service_name }} | ${{ variables.service_name }}/poetry.lock"
                  location: "${{ variables.service_name }}/.venv"
                  debug: true
              displayName: cache python dependencies
