name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/mm-apm-2214-support-configuation-of-healthcheck-suffix
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Spine-Directory-Service-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    service_base_path: ${{ variables.service_base_path }}
    short_service_name: ${{ variables.short_service_name }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    portal_api_requires_callback_url: false
    make_spec_visible: true
    deploy_review_sandbox: true
    secret_ids:
      - ptl/cis/ldap.nis1.national.ncrs.nhs.uk/key
      - ptl/cis/ldap.nis1.national.ncrs.nhs.uk/crt
      - ptl/veit07.devspineservices.nhs.uk/root-ca/crt
    config_ids:
      - /ptl/api-deployment/sds/ldap/private-key
      - /ptl/api-deployment/sds/ldap/client-cert
      - /ptl/api-deployment/sds/ldap/ca-certs
    jinja_templates:
      HOSTED_TARGET_HEALTHCHECK_SUFFIX: '/healthcheck/deep'
    apigee_deployments:
      - environment: internal-dev
        make_spec_visible: true
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              e2e_tests: true
              smoke_tests: true
              security_tests: true
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              e2e_tests: true
              smoke_tests: true
