name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/apm-1313-ecs-deploy-in-common-pipelines
      endpoint: NHSDigital
  pipelines:
  - pipeline: Spine-Directory-Service-Build
    source: Spine-Directory-Service-Build
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    service_base_path: ${{ variables.service_base_path }}
    short_service_name: ${{ variables.short_service_name }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    secret_ids:
      - "ptl/cis/ldap.nis1.national.ncrs.nhs.uk/key"
      - "ptl/cis/ldap.nis1.national.ncrs.nhs.uk/crt"
      - "ptl/veit07.devspineservices.nhs.uk/root-ca/crt"
    config_ids:
      - "/ptl/api-deployment/sds/ldap/private-key"
      - "/ptl/api-deployment/sds/ldap/client-cert"
      - "/ptl/api-deployment/sds/ldap/ca-certs"
