name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: master
      endpoint: NHSDigital
  pipelines:
  - pipeline: Spine-Directory-Service-Build
    source: Spine-Directory-Service-Build
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: project-vars.yml

extends:
  template: azure/common/common.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    proxy_path: live
    deploy_review_sandbox: false
    apigee_deployments:
      - environment: internal-dev
      - environment: internal-qa
      - environment: internal-qa-sandbox
      - environment: int
        depends_on:
          - internal_qa
          - internal_qa_sandbox
    # pre_template:
    #   - template: "templates/identity-service-templating.yml"
    #     parameters:
    #       service_name: ${{ variables.service_name }}
    #       variables_kvm: "identity-service-variables"
    #       encrypted_variables_kvm: "identity-service-variables-encrypted"
    #       identity_target_server: "identity-server"
