openapi: 3.0.0
servers:
  - description: Spine Directory Service API
    url: https://virtserver.swaggerhub.com/kainos_nhsnia/SDS_API/1.0.0
info:
  version: "1.0.0"
  title: Spine Directory Service API
  description: "## Overview\n
    Use this API to access the [Spine Directory Services (SDS)](https://digital.nhs.uk/services/spine) - an endpoint and identifier directory for Spine and Spine connected systems, containing information on accredited systems, services and NHS registered users.\n\n
    GP Connect provider and consumer systems are registered in SDS in order to enable: \n
    * consumer systems to look up provider system’s ASID and endpoint information \n
    * the Spine Secure Proxy to allow or deny requests based on known identifier and endpoint information \n 
    ### Accredited Systems records\n 
    Every system that connects to the Spine has one or more “Accredited System” (AS) records in SDS, identified by an Accredited System Identifier (ASID). \n
    This ASID is unique to a system deployed in a specific organisation, so the same application deployed into three NHS organisations would typically be represented as three unique ASIDs. \n
    ### MHS records and endpoints \n
    Every GP Connect system also has one or more “MHS” records (or message handling server record), identified by Party Key and [Interaction ID](https://developer.nhs.uk/apis/gpconnect-0-7-2/integration_interaction_ids.html). \n
    MHS records of GP Connect provider systems contain the endpoint of the target practice, as defined by the [FHIR service root URL](https://developer.nhs.uk/apis/gpconnect-0-7-2/development_fhir_api_guidance.html#service-root-url). \n
    Please see [System topologies](https://developer.nhs.uk/apis/gpconnect-0-7-2/integration_system_topologies.html) for more details on the allocation of ASIDs and Party Keys. \n
    
    ## API Status \n
    This API is in [beta](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#api-status), meaning:\n- we might make breaking changes, but only if we can't avoid it, and we'll give advance notice\n- we can't guarantee availability or performance \n \n 
    If you have any other queries, please [contact us](https://digital.nhs.uk/developer/help-and-support).\n\

    ## Technology \n
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#basic-rest).\n \n 
    It also conforms to the [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir) global standard for health care data exchange.\nSpecifically, it is aligned with [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), which is built on FHIR Release 4.\n\nYou don’t need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules.\nIn particular:\n\
    - resource names are capitalised and singular, for example `/Patient` not `/patients`\n\
    - array names are singular, for example `line` not `lines` for address lines\n\
    - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object\n\n
    This API is available on the Internet, although access using NHS smartcards (see below) currently requires a connection to the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).\n\

    ## Authorisation \n
    This API uses the Unattended Access pattern.  For more information on this pattern, please see our [Security and Authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis) page within the NHS Digital Portal.


    ## Environments and testing \n
    Environment       | Base URL                                                       |\n| ----------------- | --------------------------------------------------------------\
    \ |\n| Sandbox           | `https://sandbox.api.service.nhs.uk/spine-directory-services/`\
    \    |\n| Integration test  | `https://int.api.service.nhs.uk/spine-directory-services/`\
    \        |\n| Production        | `https://api.service.nhs.uk/spine-directory-services/`\
    \                                              |\n\n
    ### Sandbox testing\nOur [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):\n\
    * is for early developer testing\n* only covers a limited set of scenarios\n
    * is stateless, so it does not actually persist any updates\n
    * is open access,so does not allow you to test authorisation\n\n
    
    For more details on sandbox testing, or to try out the sandbox using our \"Try this API\" feature, see the documentation for each endpoint.\n\n
    
    ## Integration testing \n
    Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing) is available for formal integration testing\n
    The SDS API specification has more information on this. \n     
    For more details see [integration testing with our RESTful APIs](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing-with-our-restful-apis).\n\ \n
    
    ## Onboarding\n
    You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it’s worth planning well ahead.\n\n
    To onboard for this API, follow the [Supplier Conformance Assessment List (SCAL) process.](https://digital.nhs.uk/developer/guides-and-documentation/onboarding-process#onboard-using-the-supplier-conformance-assessment-list-scal-process)\n\ \n
    When following the SCAL process, note that:\n
    * In step 9: you must conduct penetration testing to [CHECK standards](https://www.ncsc.gov.uk/information/check-penetration-testing).\n\
    * In step 10: when you complete the Service Desk Registration Form, send it to [api.management@nhs.net](mailto:api.management@nhs.net).\n
    * In step 11: submit your completed SCAL to [api.management@nhs.net](mailto:api.management@nhs.net).\n\
    * In step 14: to request production access, contact us at [api.management@nhs.net](mailto:api.management@nhs.net).\n
  " 
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /endpoint:
    get:
      summary: Request to obtain combined routing and reliability information
      operationId: getEndpoint
      description: |
        A handler for requests to obtain combined routing and reliability information.
      parameters:
        - in: query
          name: org-code
          description: The organisation code for the Spine instance that your MHS is communicating with (eg."YES-0000806")
          required: true
          schema:
            type: string
        - in: query
          name: service-id
          description: service that is being contacted and the action that is required (eg."urn:nhs:names:services:psis:REPC_IN150016UK05")
          required: true
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/fhir+json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Endpoint'
            application/fhir+xml:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Endpoint'
        '400':
          description: bad input parameter
  /healthcheck:
    get:
      summary: Health check endpoint
      description: This endpoint just returns a HTTP 200 response and does no further processing. This endpoint is intended to be used by load balancers/other infrastructure to check that the server is running.
      operationId: getHealthcheck
      responses:
        "200":
          description: The only response this endpoint returns.
components:
  schemas:
    Endpoint:
      type: object
      description: "A FHIR endpoint that will return the routing and reliability information from the spine route lookup"
      required:
        - address
        - status
        - connectionType
        - payloadType
      properties:
        resourceType:
          type: string
          description: "FHIR Resource type"
          example: "Endpoint"
        id:
          type: string
          format: uuid
          example: "f0f0e921-92ca-4a88-a550-2dbb36f703af"
        extension:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
              valueString:
                  type: string
          example:
            - url: "nhsMHSSyncReplyMode"
              valueString: "MSHSignalsOnly"
            - url: "nhsMHSRetryInterval"
              valueString: "PT1M"
            - url: "nhsMHSRetries"
              valueString: "2"
            - url: "nhsMHSPersistDuration"
              valueString: "PT5M"       
            - url: "nhsMHSDuplicateElimination"
              valueString: "always"
            - url: "nhsMHSAckRequested"
              valueString: "always"
        identifier:
          type: array
          items: 
            type: object
            properties:
              system:
                type: string
              value:
                type: string
          example:
            - system: "https://fhir.nhs.uk/Id/nhsEndpointServiceId"
              value: "urn:nhs:names:services:psis:REPC_IN150016UK0"
            - system: "https://fhir.nhs.uk/Id/nhsMhsFQD"
              value: "192.168.128.11"
            - system: "https://fhir.nhs.uk/Id/nhsMhsEndPoint"
              value: "https://192.168.128.11/reliablemessaging/reliablerequest"
            - system: "https://fhir.nhs.uk/Id/nhsMhsPartyKey"
              value: "R8008-0000806"
            - system: "https://fhir.nhs.uk/Id/nhsMhsCPAId"
              value: "S20001A000182"
            - system: "https://fhir.nhs.uk/Id/nhsSpineASID"
              value: "227319907548"
        status:
          type: string
          enum:
            - active
            - suspended 
            - error 
            - off 
            - entered-in-error 
            - test
          example: "active"
        connectionType:
          type: string
        managingOrganization:
          type: object
          properties:
            system:
              type: string
              example: "https://fhir.nhs.uk/Id/ods-organization-code"
            value:
              type: string
              example: "R8008"
        payloadType:
          type: object
          properties:
            system:
              type: string
              example: "http://terminology.hl7.org/CodeSystem/endpoint-payload-type"
            code:
              type: string
              example: "any"
            display:
              type: string
              example: "any"
        address:
          type: string
          example: "https://192.168.128.11/"
      xml:
        name: Endpoint
