#Common env variables for outbound
SDS_SERVER_PORT: "9000"
SDS_LOG_LEVEL: NOTSET
SDS_LDAP_URL: ldap://192.168.128.11 #SDS address from OpenTest
SDS_LDAP_SEARCH_BASE: ou=services,o=nhs
SDS_LDAP_DISABLE_TLS: "True"
SDS_LDAP_CONNECTION_RETRIES: "3"
SDS_LDAP_LAZY_CONNECTION: "True"

#User-specific env variables
SDS_SECRET_PARTY_KEY: AXXXXX-XXXXXXX #put your party key here (OpenTest)
SDS_SECRET_CLIENT_CERT: |
  -----BEGIN CERTIFICATE-----
#put your endpoint certificate here (OpenTest) - remember to put two spaces of indentation for the whole length of certificate (see line above)
  -----END CERTIFICATE-----
SDS_SECRET_CLIENT_KEY: |
  -----BEGIN RSA PRIVATE KEY-----
#put your endpoint private key here (OpenTest)
  -----END RSA PRIVATE KEY-----
SDS_SECRET_CA_CERTS: |
  -----BEGIN CERTIFICATE-----
#put your Endpoint issuing subCA certificate here (OpenTest)
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
#put your Root CA certificate here (OpenTest)
  -----END CERTIFICATE-----
