name: Unit Tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker/sds-api/spine-directory-service/sds

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9.21
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.21
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
        with:
          version: 2021.5.29
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: Test with pytest
        run: |
          pipenv run unittests-sds
